import {
  Product,
  ServiceItem,
  Sale,
  Booking,
  CashSession,
  InventoryMovement,
  Customer,
  AuditLog,
  UserProfile,
  UserRole,
  AiActionProposal,
  MarketingCampaign,
  PromoVoucher,
  BankSlipRecord,
  StaffPinAccount,
  EmployeeProfile,
  StaffPermissions,
  TaskItem,
  ApprovalRequest,
  CommissionRecord,
  TrainingCourse,
  StaffActivityLog,
} from '../types';
import { hashSync } from './security';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'BEA-LASH-SERUM',
    name: 'Lash Serum บำรุงขนตาและคิ้วสูตรพรีเมียม',
    category: 'ความงาม (Beauty)',
    price: 890,
    cost: 380,
    stock: 20,
    reorder: 5,
    barcode: '8851959132014',
    image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80',
    active: true,
    is_flash_sale: true,
    flash_sale_price: 590,
    flash_sale_stock_limit: 20,
    flash_sale_sold_count: 14,
  },
  {
    id: 'prod-002',
    sku: 'BEA-LIP-GLOSS',
    name: 'Lip Gloss Organic Rose Tint',
    category: 'ความงาม (Beauty)',
    price: 690,
    cost: 290,
    stock: 30,
    reorder: 8,
    barcode: '8850123456789',
    image_url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&q=80',
    active: true,
    is_flash_sale: true,
    flash_sale_price: 450,
    flash_sale_stock_limit: 30,
    flash_sale_sold_count: 22,
  },
  {
    id: 'prod-003',
    sku: 'BEA-TONER-CALM',
    name: 'Toner Calming Herbal Mist 150ml',
    category: 'ความงาม (Beauty)',
    price: 590,
    cost: 240,
    stock: 18,
    reorder: 6,
    barcode: '8859990001111',
    image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&q=80',
    active: true,
    is_flash_sale: true,
    flash_sale_price: 390,
    flash_sale_stock_limit: 15,
    flash_sale_sold_count: 11,
  },
  {
    id: 'prod-004',
    sku: 'BEV-COFFEE-BREW',
    name: 'Coffee Cold Brew Specialty',
    category: 'เครื่องดื่ม (Food & Drink)',
    price: 45,
    cost: 18,
    stock: 45,
    reorder: 10,
    barcode: '8850987654321',
    image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&q=80',
    active: true,
  },
  {
    id: 'prod-005',
    sku: 'BEV-MATCHA-LATTE',
    name: 'Matcha Latte เกียวโตแท้ 100%',
    category: 'เครื่องดื่ม (Food & Drink)',
    price: 65,
    cost: 26,
    stock: 50,
    reorder: 10,
    barcode: '8854445556667',
    image_url: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=400&q=80',
    active: true,
    is_flash_sale: true,
    flash_sale_price: 39,
    flash_sale_stock_limit: 50,
    flash_sale_sold_count: 38,
  },
  {
    id: 'prod-006',
    sku: 'SNK-ORGANIC-CHIPS',
    name: 'Snack ขนมอบกรอบธัญพืชออร์แกนิก',
    category: 'ขนมขบเคี้ยว (Snack)',
    price: 35,
    cost: 15,
    stock: 25,
    reorder: 8,
    barcode: '8857778889990',
    image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&q=80',
    active: true,
  },
  {
    id: 'prod-007',
    sku: 'CARE-SERUM-HAIR',
    name: 'EQUAL1 เคราตินซีรั่มบำรุงผมเข้มข้น 100มล.',
    category: 'ความงาม (Beauty)',
    price: 350,
    cost: 160,
    stock: 25,
    reorder: 6,
    barcode: '8853332221114',
    image_url: 'https://images.unsplash.com/photo-1608248597359-001096759c5d?w=400&q=80',
    active: true,
    is_flash_sale: true,
    flash_sale_price: 249,
    flash_sale_stock_limit: 25,
    flash_sale_sold_count: 18,
  },
  {
    id: 'prod-008',
    sku: 'CARE-OIL-CUTICLE',
    name: 'Cuticle Oil กลิ่นอโรม่าลาเวนเดอร์ 15มล.',
    category: 'ความงาม (Daily Use)',
    price: 190,
    cost: 85,
    stock: 22,
    reorder: 8,
    barcode: '8858889990002',
    image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80',
    active: true,
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-001',
    name: 'Classic Natural Lash Eyelash Extension (ต่อขนตาคลาสสิค)',
    category: 'ต่อขนตา (Lash)',
    description: 'ต่อขนตาเส้นต่อเส้น สวยเป็นธรรมชาติ เบาสบายตา สไตล์ญี่ปุ่น ด้วยกาวมาตรฐานพรีเมียม',
    duration_minutes: 60,
    price: 790,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=600&q=80',
  },
  {
    id: 'srv-002',
    name: 'Japanese Gel Nail Art & Spa (ทาสีเจล & สปามือสไตล์ญี่ปุ่น)',
    category: 'ทำเล็บ (Nail)',
    description: 'ตัดแต่งทรง ตัดหนัง สปาเกลือหิมาลายัน พร้อมทาสีเจลนำเข้าจากญี่ปุ่น ติดทนนาน',
    duration_minutes: 45,
    price: 490,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=600&q=80',
  },
  {
    id: 'srv-003',
    name: '6D Microblading Eyebrows (ฝังสีคิ้วลายเส้น 6 มิติ)',
    category: 'สักคิ้ว & ปาก (PMU)',
    description: 'ออกแบบทรงคิ้วให้รับกับรูปหน้า สีออร์แกนิคจากเยอรมนี ลายเส้นพริ้วสวยสมจริง',
    duration_minutes: 120,
    price: 2900,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=600&q=80',
  },
  {
    id: 'srv-004',
    name: 'Minimal Fine-Line Tattoo (สักมินิมอลลายเส้นละเอียด 5x5ซม.)',
    category: 'สักลาย (Tattoo)',
    description: 'ใช้เข็มสักฆ่าเชื้อแบบใช้ครั้งเดียว หมึกสักเกรดการแพทย์ ปลอดภัย สะอาด มาตรฐานสากล',
    duration_minutes: 90,
    price: 1500,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?w=600&q=80',
  },
  {
    id: 'srv-005',
    name: 'Keratin Hair Treatment & Blow Dry (ทรีทเม้นท์เคราตินสปาผม)',
    category: 'ผม & สปา (Hair)',
    description: 'ฟื้นฟูผมแห้งเสีย นุ่มสลวย เงางาม มีน้ำหนัก พร้อมไดร์เซ็ตทรง',
    duration_minutes: 60,
    price: 690,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&q=80',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    name: 'คุณนันท์นภัส อาธาน',
    phone: '081-234-5678',
    email: 'nannapatartharn@gmail.com',
    points: 340,
    tier: '1Service Elite',
    created_at: '2026-09-01T10:00:00Z',
    password_hash: hashSync('Member1234!'),
    delivery_address: 'คอนโดเมืองเอก ตึก B ชั้น 8 ห้อง 804 ซอยพหลโยธิน 87',
  },
  {
    id: 'cust-002',
    name: 'คุณพัชราภรณ์ วงศ์สวัสดิ์',
    phone: '089-876-5432',
    email: 'patchara@example.com',
    points: 120,
    tier: '1Mart VIP',
    created_at: '2026-09-10T14:30:00Z',
    password_hash: hashSync('Member1234!'),
    delivery_address: 'บ้านเลขที่ 124/8 หมู่บ้านสัมมากร รามคำแหง 112',
  },
  {
    id: 'cust-003',
    name: 'Walk-in Customer (ลูกค้าทั่วไปหน้าร้าน)',
    phone: '',
    email: '',
    points: 0,
    tier: 'EQUAL',
    created_at: '2026-09-01T08:00:00Z',
  },
];

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'usr-owner-01',
    organization_id: 'org-equal1-main',
    display_name: 'คุณพิมพ์พร (Owner)',
    role: 'owner',
    active: true,
    email: 'owner@equal1.com',
    phone: '080-000-0001',
  },
  {
    id: 'usr-cashier-01',
    organization_id: 'org-equal1-main',
    display_name: 'สมศรี (Cashier & POS)',
    role: 'cashier',
    active: true,
    email: 'cashier1@equal1.com',
  },
  {
    id: 'usr-stylist-01',
    organization_id: 'org-equal1-main',
    display_name: 'ช่างเมย์ (Master Stylist & Lash)',
    role: 'beauty_staff',
    active: true,
    email: 'may.stylist@equal1.com',
  },
  {
    id: 'usr-delivery-01',
    organization_id: 'org-equal1-main',
    display_name: 'พี่นก (Delivery Rider)',
    role: 'delivery',
    active: true,
    email: 'rider1@equal1.com',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book-1001',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    service_id: 'srv-001',
    service_name: 'Classic Natural Lash Eyelash Extension (ต่อขนตาคลาสสิค)',
    customer_name: 'คุณนันท์นภัส อาธาน',
    customer_phone: '081-234-5678',
    starts_at: new Date(Date.now() + 3600000 * 2).toISOString(),
    duration_minutes: 60,
    technician_name: 'ช่างเมย์ (Master Stylist)',
    technician_id: 'usr-stylist-01',
    status: 'confirmed',
    price: 790,
    notes: 'ขอทรงธรรมชาติ ขนตาสั้น',
  },
  {
    id: 'book-1002',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    service_id: 'srv-002',
    service_name: 'Japanese Gel Nail Art & Spa (ทาสีเจล & สปามือสไตล์ญี่ปุ่น)',
    customer_name: 'คุณพัชราภรณ์ วงศ์สวัสดิ์',
    customer_phone: '089-876-5432',
    starts_at: new Date(Date.now() + 3600000 * 4).toISOString(),
    duration_minutes: 45,
    technician_name: 'ช่างเมย์ (Master Stylist)',
    technician_id: 'usr-stylist-01',
    status: 'requested',
    price: 490,
    notes: 'เน้นสีเอิร์ธโทน',
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-20260928-001',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    channel: 'pos',
    status: 'completed',
    payment_status: 'paid',
    payment_method: 'promptpay',
    subtotal: 110,
    discount: 0,
    delivery_fee: 0,
    total: 110,
    customer_name: 'Walk-in Customer',
    receipt_number: 'REC-20260928-0001',
    items: [
      {
        id: 'si-1',
        sale_id: 'sale-20260928-001',
        product_id: 'prod-003',
        name: 'เอสเพรสโซ่ ลาเต้ เย็น (Iced Latte)',
        sku: 'BEV-COFFEE-LATTE',
        quantity: 2,
        unit_price: 55,
        unit_cost: 22,
        line_total: 110,
      },
    ],
  },
  {
    id: 'sale-20260928-002',
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    channel: 'delivery',
    status: 'preparing',
    payment_status: 'paid',
    payment_method: 'promptpay',
    subtotal: 219,
    discount: 20,
    delivery_fee: 25,
    total: 224,
    customer_name: 'คุณนันท์นภัส อาธาน',
    customer_phone: '081-234-5678',
    delivery_address: 'คอนโดเมืองเอก ตึก B ชั้น 8 ห้อง 804',
    receipt_number: 'REC-20260928-0002',
    items: [
      {
        id: 'si-2',
        sale_id: 'sale-20260928-002',
        product_id: 'prod-004',
        name: 'มันฝรั่งทอดกรอบ โนริสาหร่าย 50ก.',
        sku: 'SNK-CHIPS-NORI',
        quantity: 2,
        unit_price: 32,
        unit_cost: 20,
        line_total: 64,
      },
      {
        id: 'si-3',
        sale_id: 'sale-20260928-002',
        product_id: 'prod-003',
        name: 'เอสเพรสโซ่ ลาเต้ เย็น (Iced Latte)',
        sku: 'BEV-COFFEE-LATTE',
        quantity: 1,
        unit_price: 55,
        unit_cost: 22,
        line_total: 55,
      },
      {
        id: 'si-4',
        sale_id: 'sale-20260928-002',
        product_id: 'prod-002',
        name: 'น้ำดื่ม EQUAL1 คริสตัล 600มล.',
        sku: 'BEV-WATER-600',
        quantity: 10,
        unit_price: 10,
        unit_cost: 4.5,
        line_total: 100,
      },
    ],
  },
];

export const INITIAL_CASH_SESSIONS: CashSession[] = [
  {
    id: 'shift-20260928-01',
    branch_id: 'br-main',
    user_id: 'usr-cashier-01',
    user_name: 'สมศรี (Cashier & POS)',
    opened_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    opening_cash: 2000,
    status: 'open',
  },
];

export const INITIAL_MOVEMENTS: InventoryMovement[] = [
  {
    id: 'mov-001',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    product_id: 'prod-003',
    product_name: 'เอสเพรสโซ่ ลาเต้ เย็น (Iced Latte)',
    sku: 'BEV-COFFEE-LATTE',
    quantity: -2,
    before_stock: 27,
    after_stock: 25,
    reason: 'POS_CHECKOUT_SALE',
    user_name: 'สมศรี (Cashier)',
    reference_id: 'sale-20260928-001',
  },
];

export const INITIAL_AUDIT: AuditLog[] = [
  {
    id: 'aud-001',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    actor_name: 'สมศรี (Cashier & POS)',
    action: 'CASH_SESSION_OPEN',
    entity_type: 'cash_sessions',
    entity_id: 'shift-20260928-01',
    details: { opening_cash: 2000, branch: 'Main Branch' },
  },
  {
    id: 'aud-002',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    actor_name: 'สมศรี (Cashier & POS)',
    action: 'POS_SALE_COMPLETED',
    entity_type: 'sales',
    entity_id: 'sale-20260928-001',
    details: { total: 110, method: 'promptpay', items: 2 },
  },
];

export const INITIAL_AI_ACTIONS: AiActionProposal[] = [
  {
    id: 'act-001',
    type: 'reorder',
    title: 'สั่งซื้อเติมสต๊อก: มัทฉะลาเต้ แท้จากเกียวโต (Iced Matcha)',
    explanation: 'สต๊อกปัจจุบันเหลือ 4 แก้ว ซึ่งต่ำกว่า Reorder point ที่กำหนดไว้ (8 แก้ว) และมียอดขายเฉลี่ย 12 แก้ว/สัปดาห์',
    recommendation: 'สร้างใบสั่งซื้อ (Purchase Order) จำนวน 24 ถุงวัตถุดิบ จากซัพพลายเออร์ Kyoto Supply เพื่อไม่ให้ของขาดช่วงสุดสัปดาห์',
    status: 'proposed',
    dataPayload: { sku: 'BEV-GREEN-TEA', reorder_qty: 24, estimated_cost: 624 },
    created_at: new Date().toISOString(),
  },
  {
    id: 'act-002',
    type: 'promotion',
    title: 'แนะนำโปรโมชั่น Combo: แซนด์วิชเนยสด + กาแฟลาเต้เย็น',
    explanation: 'ตรวจพบว่าลูกค้าที่ซื้อลาเต้เย็น 65% สั่งคู่กับเบเกอรี่ แต่ยังไม่มีราคาแพ็กเกจส่งเสริมการขาย',
    recommendation: 'จัดเซ็ตคู่ 85 บาท (จากปกติ 94 บาท) เฉพาะช่วงเวลา 07:00 - 10:30 น. เพื่อเพิ่ม Basket Size หน้าร้าน',
    status: 'proposed',
    dataPayload: { combo_items: ['BEV-COFFEE-LATTE', 'SNK-BREAD-BUTTER'], combo_price: 85 },
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: 'camp-001',
    title: '🔥 Flash Sale ดับร้อน ลดสูงสุด 35%',
    subtitle: 'เครื่องดื่มชงสด และ เบเกอรี่ฮอกไกโด ซื้อคู่รับส่วนลดทันที',
    badge: 'FLASH',
    type: 'banner',
    image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800&q=80',
    target_link: 'customer-shop',
    discount_text: 'ลดสูงสุด 35%',
    active: true,
    start_date: '2026-09-01',
    end_date: '2026-10-31',
    views_count: 1420,
    clicks_count: 318,
  },
  {
    id: 'camp-002',
    title: '✨ Exclusive Salon Spa Package',
    subtitle: 'ทำเล็บเจลสไตล์ลูกคุณ + สปามือพาราฟิน เพียง 790 บาท',
    badge: 'HOT',
    type: 'banner',
    image_url: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=800&q=80',
    target_link: 'customer-beauty',
    discount_text: 'ราคาพิเศษ ฿790 (จาก ฿1,090)',
    active: true,
    start_date: '2026-09-15',
    end_date: '2026-10-15',
    views_count: 980,
    clicks_count: 245,
  },
  {
    id: 'camp-003',
    title: '🎉 สะสมแต้มคูณสอง (2X Points Weekend)',
    subtitle: 'ทุกวันเสาร์-อาทิตย์ สำหรับสมาชิก EQUAL1 Club ทุกระดับ',
    badge: 'EXCLUSIVE',
    type: 'banner',
    image_url: 'https://images.unsplash.com/photo-1555421689-491a97ff2040?w=800&q=80',
    target_link: 'customer-shop',
    discount_text: 'แต้ม X2 ทันที',
    active: true,
    start_date: '2026-09-20',
    end_date: '2026-11-30',
    views_count: 812,
    clicks_count: 190,
  },
];

export const INITIAL_VOUCHERS: PromoVoucher[] = [
  {
    id: 'vouch-001',
    code: 'WELCOME50',
    title: 'ต้อนรับลูกค้าใหม่ ลดทันที 50 บาท',
    discount_type: 'fixed',
    discount_value: 50,
    min_spend: 200,
    expires_at: '2026-12-31',
    usage_limit: 500,
    used_count: 142,
    active: true,
  },
  {
    id: 'vouch-002',
    code: 'EQUAL10',
    title: 'ส่วนลด 10% ทุกรายการในมินิมาร์ท',
    discount_type: 'percent',
    discount_value: 10,
    min_spend: 150,
    max_discount: 100,
    expires_at: '2026-10-31',
    usage_limit: 200,
    used_count: 67,
    active: true,
  },
  {
    id: 'vouch-003',
    code: 'SALON100',
    title: 'ส่วนลด 100 บาท สำหรับบริการเสริมสวย',
    discount_type: 'fixed',
    discount_value: 100,
    min_spend: 500,
    expires_at: '2026-11-15',
    usage_limit: 100,
    used_count: 38,
    active: true,
  },
];

export const INITIAL_SLIP_RECORDS: BankSlipRecord[] = [
  {
    id: 'slip-001',
    sale_id: 'sale-20260928-001',
    order_id: 'ORD-98214',
    slip_image_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&q=80',
    bank_name: 'KBANK (กสิกรไทย)',
    sender_name: 'นาย ธีรภัทร วงศ์เจริญ',
    sender_account: 'xxx-2-58192-x',
    receiver_account: '098-765-4321 (PromptPay EQUAL1)',
    amount: 110,
    transaction_ref: '014234123456789012',
    transferred_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    verified_at: new Date(Date.now() - 3600000 * 2.9).toISOString(),
    verification_status: 'verified',
    verification_note: 'สลิปถูกต้อง รหัสอ้างอิงตรง ยอดเงิน ฿110 ตรงกับยอดบิล',
    verified_by: 'ระบบ AI Scan & สมศรี (Cashier)',
  },
  {
    id: 'slip-002',
    sale_id: 'sale-20260928-002',
    order_id: 'ORD-98215',
    slip_image_url: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=500&q=80',
    bank_name: 'SCB (ไทยพาณิชย์)',
    sender_name: 'น.ส. ธนัชชา กิจประเสริฐ',
    sender_account: 'xxx-1-90432-x',
    receiver_account: '098-765-4321 (PromptPay EQUAL1)',
    amount: 450,
    transaction_ref: '20260928SCB876543210',
    transferred_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    verified_at: new Date(Date.now() - 3600000 * 1.9).toISOString(),
    verification_status: 'verified',
    verification_note: 'สลิป SCB Easy ตรงกับออเดอร์ค่านวดหน้า & สปา',
    verified_by: 'ระบบ AI Scan',
  },
];

export const INITIAL_STAFF_PINS: StaffPinAccount[] = [
  {
    id: 'usr-owner-01',
    name: 'คุณพิมพ์พร (Owner & Founder)',
    role: 'owner',
    pin: '9999',
    pin_hash: hashSync('9999'),
    avatar: '👑',
    active: true,
  },
  {
    id: 'usr-manager-01',
    name: 'คุณกิตติศักดิ์ (Store Manager)',
    role: 'manager',
    pin: '4444',
    pin_hash: hashSync('4444'),
    avatar: '👔',
    active: true,
  },
  {
    id: 'usr-cashier-01',
    name: 'สมศรี (Senior Cashier & POS)',
    role: 'cashier',
    pin: '1234',
    pin_hash: hashSync('1234'),
    avatar: '🛒',
    active: true,
  },
  {
    id: 'usr-stylist-01',
    name: 'ช่างเมย์ (Master Stylist)',
    role: 'beauty_staff',
    pin: '2345',
    pin_hash: hashSync('2345'),
    avatar: '✂️',
    active: true,
  },
  {
    id: 'usr-delivery-01',
    name: 'สมชาย (Fast Delivery Rider)',
    role: 'delivery',
    pin: '3456',
    pin_hash: hashSync('3456'),
    avatar: '🛵',
    active: true,
  },
  {
    id: 'usr-stock-01',
    name: 'มานะ (Inventory & Stock)',
    role: 'stock',
    pin: '7890',
    pin_hash: hashSync('7890'),
    avatar: '📦',
    active: true,
  },
];

// Helper to generate default permissions by role
export const getRoleDefaultPermissions = (role: UserRole): StaffPermissions => {
  if (role === 'owner' || role === 'super_admin') {
    return {
      pos: { create_order: true, edit_cart: true, apply_discount: true, void_order: true, refund: true },
      stock: { view_stock: true, receive_stock: true, adjust_stock: true, delete_movement: true },
      customer: { view_customer: true, create_customer: true, add_notes: true, export_data: true },
      finance: { view_daily_sales: true, view_profit: true, manage_cash_shift: true },
      team: { manage_tasks: true, approve_requests: true, view_other_salaries: true },
    };
  }
  if (role === 'manager' || role === 'supervisor') {
    return {
      pos: { create_order: true, edit_cart: true, apply_discount: true, void_order: true, refund: true },
      stock: { view_stock: true, receive_stock: true, adjust_stock: true, delete_movement: false },
      customer: { view_customer: true, create_customer: true, add_notes: true, export_data: false },
      finance: { view_daily_sales: true, view_profit: false, manage_cash_shift: true },
      team: { manage_tasks: true, approve_requests: true, view_other_salaries: false },
    };
  }
  if (role === 'cashier' || role === 'sales') {
    return {
      pos: { create_order: true, edit_cart: true, apply_discount: true, void_order: false, refund: false },
      stock: { view_stock: true, receive_stock: false, adjust_stock: false, delete_movement: false },
      customer: { view_customer: true, create_customer: true, add_notes: true, export_data: false },
      finance: { view_daily_sales: true, view_profit: false, manage_cash_shift: true },
      team: { manage_tasks: false, approve_requests: false, view_other_salaries: false },
    };
  }
  if (role === 'beauty_staff' || role === 'service_staff') {
    return {
      pos: { create_order: true, edit_cart: false, apply_discount: false, void_order: false, refund: false },
      stock: { view_stock: true, receive_stock: false, adjust_stock: false, delete_movement: false },
      customer: { view_customer: true, create_customer: true, add_notes: true, export_data: false },
      finance: { view_daily_sales: false, view_profit: false, manage_cash_shift: false },
      team: { manage_tasks: false, approve_requests: false, view_other_salaries: false },
    };
  }
  if (role === 'stock') {
    return {
      pos: { create_order: false, edit_cart: false, apply_discount: false, void_order: false, refund: false },
      stock: { view_stock: true, receive_stock: true, adjust_stock: true, delete_movement: false },
      customer: { view_customer: false, create_customer: false, add_notes: false, export_data: false },
      finance: { view_daily_sales: false, view_profit: false, manage_cash_shift: false },
      team: { manage_tasks: true, approve_requests: false, view_other_salaries: false },
    };
  }
  // Default minimal
  return {
    pos: { create_order: false, edit_cart: false, apply_discount: false, void_order: false, refund: false },
    stock: { view_stock: true, receive_stock: false, adjust_stock: false, delete_movement: false },
    customer: { view_customer: true, create_customer: false, add_notes: false, export_data: false },
    finance: { view_daily_sales: false, view_profit: false, manage_cash_shift: false },
    team: { manage_tasks: false, approve_requests: false, view_other_salaries: false },
  };
};

export const INITIAL_EMPLOYEES: EmployeeProfile[] = [
  {
    id: 'emp-001',
    name: 'คุณพิมพ์พร ไชยโย',
    nickname: 'พิมพ์ (Owner)',
    position: 'Founder & CEO (เจ้าของกิจการ)',
    branch_id: 'br-001',
    branch_name: 'สำนักงานใหญ่ / ทุกสาขา',
    role: 'owner',
    status: 'active',
    attendance_status: 'clocked_in',
    phone: '080-000-0001',
    email: 'owner@equal1.com',
    avatar: '👑',
    skills: ['Business Strategy', 'Financial Control', 'Multi-Branch Management', 'Brand Architecture'],
    services_can_perform: ['srv-001', 'srv-002', 'srv-003', 'srv-004'],
    commission_rate_pct: 0,
    base_salary: 120000,
    joined_date: '2025-01-01',
    today_sales: 28420,
    today_services_count: 0,
    today_commission: 0,
    monthly_commission: 0,
    last_clock_in: '2026-09-29T08:30:00Z',
    permissions: getRoleDefaultPermissions('owner'),
    completed_training_courses: ['tr-001', 'tr-002', 'tr-003', 'tr-004', 'tr-005'],
  },
  {
    id: 'emp-002',
    name: 'คุณกิตติศักดิ์ พงศ์ไพศาล',
    nickname: 'กิต (Manager)',
    position: 'General Store Manager (ผู้จัดการสาขา)',
    branch_id: 'br-001',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
    role: 'manager',
    status: 'active',
    attendance_status: 'clocked_in',
    phone: '081-999-4444',
    email: 'kittisak.manager@equal1.com',
    avatar: '👔',
    skills: ['Store Operations', 'Cash Shift Balancing', 'Conflict Resolution', 'Inventory Audit'],
    services_can_perform: [],
    commission_rate_pct: 3,
    base_salary: 38000,
    joined_date: '2025-03-15',
    today_sales: 14200,
    today_services_count: 0,
    today_commission: 426,
    monthly_commission: 8940,
    last_clock_in: '2026-09-29T08:45:00Z',
    permissions: getRoleDefaultPermissions('manager'),
    completed_training_courses: ['tr-001', 'tr-002', 'tr-004', 'tr-005'],
  },
  {
    id: 'emp-003',
    name: 'คุณเมทินี ศรีสวัสดิ์',
    nickname: 'ช่างเมย์',
    position: 'Master Lash & Brow Artist (ช่างต่อขนตาอาวุโส)',
    branch_id: 'br-002',
    branch_name: 'สาขา METUR DIARY BEAU (Beauty Bar)',
    role: 'beauty_staff',
    status: 'active',
    attendance_status: 'clocked_in',
    phone: '089-111-2345',
    email: 'may.lash@equal1.com',
    avatar: '✂️',
    skills: ['Classic Lash Extension', 'Russian Volume 6D', 'Wet Look Lash', 'Lash Lifting & Tint', 'Brow Henna'],
    services_can_perform: ['srv-001', 'srv-002', 'srv-003'],
    commission_rate_pct: 30, // 30% for Beauty Service
    base_salary: 18000,
    joined_date: '2025-06-01',
    today_sales: 4820,
    today_services_count: 4,
    today_commission: 840,
    monthly_commission: 16420,
    last_clock_in: '2026-09-29T09:00:00Z',
    permissions: getRoleDefaultPermissions('beauty_staff'),
    completed_training_courses: ['tr-002', 'tr-004', 'tr-005'],
  },
  {
    id: 'emp-004',
    name: 'คุณสมศรี เพ็ญสิริ',
    nickname: 'สมศรี',
    position: 'Senior Cashier & Customer Experience',
    branch_id: 'br-001',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
    role: 'cashier',
    status: 'active',
    attendance_status: 'clocked_in',
    phone: '086-333-1234',
    email: 'somsri.pos@equal1.com',
    avatar: '🛒',
    skills: ['POS Barcode Scanning', 'Cash Float Reconciliation', 'Voucher Redemption', 'Customer Loyalty'],
    services_can_perform: [],
    commission_rate_pct: 1.5,
    base_salary: 16500,
    joined_date: '2025-08-01',
    today_sales: 8450,
    today_services_count: 0,
    today_commission: 126.75,
    monthly_commission: 3410,
    last_clock_in: '2026-09-29T08:50:00Z',
    permissions: getRoleDefaultPermissions('cashier'),
    completed_training_courses: ['tr-001', 'tr-002'],
  },
  {
    id: 'emp-005',
    name: 'คุณมานะ มั่นคง',
    nickname: 'มานะ',
    position: 'Inventory & Logistics Supervisor (หัวหน้าคลัง)',
    branch_id: 'br-001',
    branch_name: 'คลังสินค้าส่วนกลาง & สาขาเมืองเอก',
    role: 'stock',
    status: 'active',
    attendance_status: 'clocked_in',
    phone: '084-555-7890',
    email: 'mana.stock@equal1.com',
    avatar: '📦',
    skills: ['FIFO Stock Rotation', 'Barcode Tagging', 'Supplier Inbound', 'Cold Storage Temperature Control'],
    services_can_perform: [],
    commission_rate_pct: 1.0,
    base_salary: 17500,
    joined_date: '2025-09-01',
    today_sales: 0,
    today_services_count: 0,
    today_commission: 0,
    monthly_commission: 1850,
    last_clock_in: '2026-09-29T08:00:00Z',
    permissions: getRoleDefaultPermissions('stock'),
    completed_training_courses: ['tr-003', 'tr-005'],
  },
  {
    id: 'emp-006',
    name: 'คุณสมชาย ว่องไว',
    nickname: 'สมชาย',
    position: 'Express Delivery Rider & Dispatcher',
    branch_id: 'br-001',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
    role: 'delivery',
    status: 'active',
    attendance_status: 'clocked_in',
    phone: '082-777-3456',
    email: 'somchai.delivery@equal1.com',
    avatar: '🛵',
    skills: ['Sub-15 Min Campus Delivery', 'Proof of Delivery Photo', 'Cash on Delivery Collection'],
    services_can_perform: [],
    commission_rate_pct: 5.0, // ฿25 delivery fee commission
    base_salary: 15000,
    joined_date: '2025-10-15',
    today_sales: 975,
    today_services_count: 0,
    today_commission: 150,
    monthly_commission: 3750,
    last_clock_in: '2026-09-29T09:15:00Z',
    permissions: getRoleDefaultPermissions('delivery'),
    completed_training_courses: ['tr-001'],
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-001',
    title: 'ตรวจนับกาวต่อขนตา & อุปกรณ์ฆ่าเชื้อ UV Station',
    description: 'กาวต่อขนตาเปิดใช้งานแล้ว 2 ขวด เช็ควันหมดอายุ และนำคีม Tweezers อบฆ่าเชื้อ 45 นาที',
    branch_id: 'br-002',
    created_by_name: 'คุณกิตติศักดิ์ (Manager)',
    assigned_to_id: 'emp-003',
    assigned_to_name: 'ช่างเมย์',
    priority: 'high',
    status: 'in_progress',
    due_time: '12:00',
    category: 'cleanliness',
    checklist: [
      { id: 'chk-1', label: 'เช็ควันหมดอายุกาวต่อขนตา Lady Black & Sky Glue', completed: true },
      { id: 'chk-2', label: 'อบฆ่าเชื้อคีม Tweezers ในเครื่อง UV Sterilizer', completed: true },
      { id: 'chk-3', label: 'เช็ดทำความสะอาดเตียงต่อขนตาเตียงที่ 1-2 ด้วยน้ำยาฆ่าเชื้อ', completed: false },
    ],
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'task-002',
    title: 'เติมสินค้าเครื่องดื่มตู้แช่หลัก & จัดเรียงแบบ FIFO',
    description: 'นำโค้กและอิชิตันจากสต๊อกหลังร้านมาเติมตู้แช่ด้านหน้าให้เต็ม โดยนำล็อตเก่ามาไว้ด้านหน้า',
    branch_id: 'br-001',
    created_by_name: 'คุณพิมพ์พร (Owner)',
    assigned_to_id: 'emp-005',
    assigned_to_name: 'มานะ',
    priority: 'medium',
    status: 'todo',
    due_time: '14:00',
    category: 'inventory',
    checklist: [
      { id: 'chk-4', label: 'เบิกโค้ก 325มล. 2 ลัง (48 กระป๋อง)', completed: false },
      { id: 'chk-5', label: 'จัดเรียงเข้าตู้แช่เช็คอุณหภูมิ 4 องศาเซลเซียส', completed: false },
      { id: 'chk-6', label: 'อัปเดตยอดสต๊อกในระบบ EQUAL1 Inventory', completed: false },
    ],
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'task-003',
    title: 'เปิดร้าน & ตรวจนับเงินทอนรอบเช้า (Opening Float ฿2,000)',
    description: 'นับธนบัตรและเหรียญเงินทอนในลิ้นชักเงินสดพร้อมเปิดรอบกะ Cash Register ให้ตรงระบบ',
    branch_id: 'br-001',
    created_by_name: 'คุณกิตติศักดิ์ (Manager)',
    assigned_to_id: 'emp-004',
    assigned_to_name: 'สมศรี',
    priority: 'urgent',
    status: 'completed',
    due_time: '09:00',
    category: 'opening',
    checklist: [
      { id: 'chk-7', label: 'นับธนบัตร ฿500 (1 ใบ), ฿100 (10 ใบ), ฿50 (6 ใบ), ฿20 (10 ใบ)', completed: true },
      { id: 'chk-8', label: 'บันทึกยอดเงินเปิดกะใน Cash Register Modal', completed: true },
      { id: 'chk-9', label: 'ตรวจความพร้อมเครื่องยิงบาร์โค้ด & จอแสดงผลลูกค้า', completed: true },
    ],
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    completed_at: new Date(Date.now() - 3600000 * 4.5).toISOString(),
    verified_by: 'คุณกิตติศักดิ์ (Manager)',
  },
  {
    id: 'task-004',
    title: 'เตรียมชุดของแถมแคมเปญ Back to Campus นักศึกษา ม.รังสิต',
    description: 'จัดแพ็คคู่คูปองส่วนลดซาลอน ฿100 ใส่ถุงมินิมาร์ทสำหรับลูกค้าที่มียอดซื้อครบ ฿200',
    branch_id: 'br-001',
    created_by_name: 'คุณพิมพ์พร (Owner)',
    assigned_to_id: 'emp-004',
    assigned_to_name: 'สมศรี',
    priority: 'medium',
    status: 'todo',
    due_time: '16:00',
    category: 'general',
    checklist: [
      { id: 'chk-10', label: 'พิมพ์คูปองโค้ด EQUALWELCOME จากระบบ Marketing', completed: false },
      { id: 'chk-11', label: 'จัดเตรียม 50 ชุดไว้ข้างจุดคิดเงิน POS', completed: false },
    ],
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
];

export const INITIAL_APPROVALS: ApprovalRequest[] = [
  {
    id: 'appr-001',
    type: 'refund',
    title: 'ขอคืนเงินออเดอร์มินิมาร์ท #1042 (สินค้าชำรุด)',
    requested_by_id: 'emp-004',
    requested_by_name: 'สมศรี (Senior Cashier)',
    branch_id: 'br-001',
    details: 'ลูกค้าซื้อโยเกิร์ตแล้วพบว่าฝาฉีกขาด ขอคืนเงินสดจำนวน ฿45 พร้อมแนบสลิปเดิม',
    amount: 45,
    reference_id: 'ord-1042',
    status: 'pending',
    created_at: new Date(Date.now() - 3600000 * 1.5).toISOString(),
  },
  {
    id: 'appr-002',
    type: 'stock_adjustment',
    title: 'ขอปรับลดยอดสต๊อกกาวต่อขนตาชำรุด 1 ขวด',
    requested_by_id: 'emp-003',
    requested_by_name: 'ช่างเมย์ (Master Stylist)',
    branch_id: 'br-002',
    details: 'หัวขวดกาวอุดตันและแห้งแข็ง ไม่สามารถใช้งานต่อขนตาให้ลูกค้าได้อย่างปลอดภัย',
    amount: 450,
    reference_id: 'prod-lash-glue',
    status: 'pending',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'appr-003',
    type: 'large_discount',
    title: 'ขออนุมัติส่วนลดพิเศษ VIP 20% สำหรับคอร์สต่อขนตารายปี',
    requested_by_id: 'emp-002',
    requested_by_name: 'คุณกิตติศักดิ์ (Store Manager)',
    branch_id: 'br-002',
    details: 'คุณนันท์นภัส (1Service Elite) ต้องการต่ออายุแพ็กเกจบุฟเฟต์ ขอส่วนลด ฿800 เกินเพดานแคชเชียร์',
    amount: 800,
    reference_id: 'cust-001',
    status: 'approved',
    created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    resolved_at: new Date(Date.now() - 3600000 * 5.5).toISOString(),
    resolved_by: 'คุณพิมพ์พร (Owner)',
    resolution_note: 'อนุมัติให้คุณนันท์นภัสได้ เนื่องจากเป็นสมาชิกระดับ Elite สูงสุด',
  },
];

export const INITIAL_COMMISSIONS: CommissionRecord[] = [
  {
    id: 'comm-101',
    employee_id: 'emp-003',
    employee_name: 'ช่างเมย์',
    transaction_type: 'service',
    reference_id: 'book-1001',
    description: 'ต่อขนตา Classic Natural Lash (คุณนันท์นภัส)',
    amount_base: 1200,
    rate_pct: 30,
    commission_earned: 360,
    customer_name: 'คุณนันท์นภัส อาธาน',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    payout_status: 'approved',
  },
  {
    id: 'comm-102',
    employee_id: 'emp-003',
    employee_name: 'ช่างเมย์',
    transaction_type: 'service',
    reference_id: 'book-1002',
    description: 'Wet Look Lash & Lifting Tint (คุณพัชราภรณ์)',
    amount_base: 1600,
    rate_pct: 30,
    commission_earned: 480,
    customer_name: 'คุณพัชราภรณ์ วงศ์สวัสดิ์',
    created_at: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    payout_status: 'pending',
  },
  {
    id: 'comm-103',
    employee_id: 'emp-004',
    employee_name: 'สมศรี',
    transaction_type: 'product_sale',
    reference_id: 'ord-8891',
    description: 'ยอดขายหน้าร้าน POS รวมบิลรอบเช้า (คอมมิชชั่น 1.5%)',
    amount_base: 8450,
    rate_pct: 1.5,
    commission_earned: 126.75,
    customer_name: 'ลูกค้าทั่วไปหน้าร้าน',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    payout_status: 'approved',
  },
  {
    id: 'comm-104',
    employee_id: 'emp-006',
    employee_name: 'สมชาย',
    transaction_type: 'product_sale',
    reference_id: 'ord-9012',
    description: 'ค่าบริการจัดส่งด่วนคอนโดเมืองเอก 6 เที่ยว (฿25/เที่ยว)',
    amount_base: 150,
    rate_pct: 100,
    commission_earned: 150,
    customer_name: 'ลูกค้าหอพักเมืองเอก',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    payout_status: 'approved',
  },
];

export const INITIAL_TRAINING_COURSES: TrainingCourse[] = [
  {
    id: 'tr-001',
    code: 'POS-101',
    title: 'POS Mastery & Sub-2s PIN Switch',
    category: 'Operations',
    duration_minutes: 25,
    description: 'การเปิดรอบกะเงินสด, ยิงบาร์โค้ดสินค้า, พักบิล/เรียกคืนบิล, และการสลับพนักงานด้วย PIN 4 หลัก',
    modules_count: 4,
    badge_name: 'Certified Cashier Pro',
    required_for_roles: ['cashier', 'manager', 'sales'],
  },
  {
    id: 'tr-002',
    code: 'SEC-102',
    title: 'Customer Privacy & Zero-Plaintext Standard',
    category: 'Security',
    duration_minutes: 20,
    description: 'มาตรฐานความปลอดภัย Zero-Plaintext, การคุ้มครองรหัสผ่านลูกค้า, การปิดบังเบอร์โทรศัพท์ และการรักษาความลับทางการค้า',
    modules_count: 3,
    badge_name: 'Data Privacy Guardian',
    required_for_roles: ['owner', 'manager', 'cashier', 'beauty_staff'],
  },
  {
    id: 'tr-003',
    code: 'INV-103',
    title: 'FIFO Stock Control & Spoilage Prevention',
    category: 'Inventory',
    duration_minutes: 30,
    description: 'การตรวจรับสินค้าเข้าคลัง, การจัดเรียงสินค้าแบบ FIFO, การจัดเก็บอุณหภูมิควบคุม และการบันทึกสต๊อกชำรุด',
    modules_count: 5,
    badge_name: 'Inventory Specialist',
    required_for_roles: ['stock', 'manager'],
  },
  {
    id: 'tr-004',
    code: 'BEA-104',
    title: 'Salon Sterilization & Lash Hygiene Standards',
    category: 'Beauty',
    duration_minutes: 35,
    description: 'ขั้นตอนการฆ่าเชื้ออุปกรณ์ด้วย UV Sterilizer, การคัดกรองอาการแพ้ของลูกค้า และการให้คำแนะนำดูแลหลังต่อขนตา',
    modules_count: 4,
    badge_name: 'Master Hygiene Stylist',
    required_for_roles: ['beauty_staff', 'service_staff'],
  },
  {
    id: 'tr-005',
    code: 'AUD-105',
    title: 'Store Opening & Closing Protocols',
    category: 'Management',
    duration_minutes: 20,
    description: 'รายการตรวจสอบ 8 ข้อตอนเปิดร้าน และ 7 ข้อตอนปิดร้าน พร้อมการนับตรวจเงินสดส่วนต่าง (Cash Variance)',
    modules_count: 3,
    badge_name: 'Shift Supervisor Star',
    required_for_roles: ['manager', 'supervisor', 'cashier'],
  },
];

export const INITIAL_STAFF_ACTIVITIES: StaffActivityLog[] = [
  {
    id: 'act-001',
    timestamp: '2026-09-29T08:00:15Z',
    employee_id: 'emp-005',
    employee_name: 'มานะ (Stock)',
    action_type: 'clock_in',
    title: 'ลงเวลาเข้างาน (Clock In)',
    detail: 'สแกนเข้างานที่สาขาเมืองเอก ผ่านเครื่อง POS ประจำคลัง',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
  },
  {
    id: 'act-002',
    timestamp: '2026-09-29T08:45:10Z',
    employee_id: 'emp-002',
    employee_name: 'คุณกิตติศักดิ์ (Manager)',
    action_type: 'login',
    title: 'เข้าสู่ระบบด้วยรหัส PIN 4444',
    detail: 'ยืนยันตัวตนสิทธิ์ระดับ Store Manager',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
  },
  {
    id: 'act-003',
    timestamp: '2026-09-29T08:50:22Z',
    employee_id: 'emp-004',
    employee_name: 'สมศรี (Cashier)',
    action_type: 'checklist',
    title: 'ดำเนินการ Opening Checklist 8 รายการ',
    detail: 'ตรวจนับเงินทอนเปิดกะ ฿2,000 ครบถ้วน พร้อมเปิดให้บริการหน้าร้าน',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
  },
  {
    id: 'act-004',
    timestamp: '2026-09-29T09:00:05Z',
    employee_id: 'emp-003',
    employee_name: 'ช่างเมย์ (Stylist)',
    action_type: 'clock_in',
    title: 'ลงเวลาเข้างาน (Clock In)',
    detail: 'เข้าประจำการสเตชั่นต่อขนตา พร้อมรับคิวนัดหมาย 4 ท่าน',
    branch_name: 'สาขา METUR DIARY BEAU',
  },
  {
    id: 'act-005',
    timestamp: '2026-09-29T09:17:40Z',
    employee_id: 'emp-004',
    employee_name: 'สมศรี (Cashier)',
    action_type: 'sale_order',
    title: 'บันทึกรายการขาย POS Order #1041',
    detail: 'รับชำระเงินสด ฿185 พิมพ์ใบเสร็จย่อเรียบร้อย',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
  },
  {
    id: 'act-006',
    timestamp: '2026-09-29T10:15:30Z',
    employee_id: 'emp-003',
    employee_name: 'ช่างเมย์ (Stylist)',
    action_type: 'booking_service',
    title: 'เสร็จสิ้นบริการ Classic Lash Booking #1001',
    detail: 'ลูกค้าคุณนันท์นภัส พึงพอใจมาก ได้รับคอมมิชชั่น ฿360 (30%)',
    branch_name: 'สาขา METUR DIARY BEAU',
  },
  {
    id: 'act-007',
    timestamp: '2026-09-29T11:42:18Z',
    employee_id: 'emp-004',
    employee_name: 'สมศรี (Cashier)',
    action_type: 'request_approval',
    title: 'ยื่นคำขออนุมัติคืนเงิน Refund #1042',
    detail: 'สินค้าโยเกิร์ตชำรุด ขอคืนเงินสด ฿45 รอ Owner อนุมัติ',
    branch_name: 'สาขาเมืองเอก / รังสิต มินิมาร์ท',
  },
];

export const OPENING_CHECKLIST_TEMPLATE = [
  { id: 'op-1', label: 'ปลดล็อคประตูร้าน & เปิดระบบไฟฟ้า แอร์ แสงสว่าง' },
  { id: 'op-2', label: 'เปิดเครื่อง POS จุดขาย และทดสอบเครื่องยิงบาร์โค้ด' },
  { id: 'op-3', label: 'ตรวจนับเงินทอนเริ่มต้นในลิ้นชัก (Opening Float ฿2,000)' },
  { id: 'op-4', label: 'ตรวจสต๊อกสินค้าสำคัญ & อุปกรณ์ซาลอนพร้อมให้บริการ' },
  { id: 'op-5', label: 'ตรวจความสะอาดหน้าร้าน โต๊ะ สเตชั่นบริการ และห้องน้ำ' },
  { id: 'op-6', label: 'ตรวจอุปกรณ์ไฟฟ้า ตู้แช่ (อุณหภูมิ 2-4°C) และเครื่องฆ่าเชื้อ' },
  { id: 'op-7', label: 'ตรวจสอบคิวนัดหมายซาลอนวันนี้ในระบบ Booking Timeline' },
  { id: 'op-8', label: 'ตรวจสอบโปรโมชั่น & ป้ายสื่อสารแคมเปญที่เปิดใช้งาน' },
];

export const CLOSING_CHECKLIST_TEMPLATE = [
  { id: 'cl-1', label: 'ตรวจสรุปยอดขายสะสมประจำวันผ่าน POS Terminal' },
  { id: 'cl-2', label: 'นับเงินสดจริงในลิ้นชัก เทียบกับ Expected Cash' },
  { id: 'cl-3', label: 'กระทบยอดสลิปโอนเงิน QR Payment & บัตรเครดิต' },
  { id: 'cl-4', label: 'ตรวจสอบรายการสินค้าคงเหลือ & แจ้งเตือนของขาด' },
  { id: 'cl-5', label: 'ตรวจสอบสถานะออเดอร์ค้างส่งทั้งหมดให้เสร็จสิ้น' },
  { id: 'cl-6', label: 'ทำความสะอาดสเตชั่น อบฆ่าเชื้ออุปกรณ์ และทิ้งขยะ' },
  { id: 'cl-7', label: 'ปิดระบบ POS, ล็อคลิ้นชักเงินสด และปิดรอบกะประจำวัน' },
];


